### ISSUE TITLE
nerd tree overlapping by the open tab

### ISSUE THREAD

**Issue by ghost** [bcampolo/nvim-starter-kit#25]
<img width="1500" alt="Screenshot 2024-12-07 at 19 29 55" src="https://github.com/user-attachments/assets/7e1de837-68fb-4165-b28e-933c8db6b31c">

**Comment by ghost** [comment]
hello maybe there is a way to resize the window

**Comment by bcampolo** [comment]
If I understand your correctly, what you are showing is the default behavior.  The tab is not overlapping.  What you are seeing is two v-splits, the left has nvim-tree and the right is an open file buffer.  The left split just isn't wide enough to show the full text.  On the nvim-tree GitHub page it shows how to set a fixed with or you can try something dynamic like this: 
https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes#toggle-adaptive-width

Let me know how it turns out! 😀
